dist: xenial
language: python
python:
 - "3.7"

before_install:
 - DATA_MODEL_NAME=`echo $TRAVIS_REPO_SLUG | awk -F'.' '{print $2}'`
 - echo $DATA_MODEL_NAME


install:
 - npm install -g ajv-cli
 - cd .. && mkdir integration && cd integration
 - git clone https://github.com/smart-data-models/tools
 - cd tools/validator && pip3 install -r requirements.txt
 - cd $TRAVIS_BUILD_DIR/../integration
 - git clone --recurse-submodules https://github.com/smart-data-models/dataModels
 - cd dataModels/specs/$DATA_MODEL_NAME
 - rm -Rf *
 - cd $TRAVIS_BUILD_DIR/ && cp -R * ../integration/dataModels/specs/$DATA_MODEL_NAME/
 - docker run --name mongodb -d mongo:3.6
 - docker run -d --name orion1 --link mongodb:mongodb -p 1026:1026 fiware/orion -dbhost mongodb
  
 
script:
 - python3 ../integration/tools/validator/main.py ../integration/dataModels/ --noLD
 
  
notifications:
  on_success: change
  on_failure: always
